/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogBrilhoContraste.java
 *
 * Created on 15/09/2014, 15:57:58
 */
package br.com.imagetoolkit.tela;

import br.com.imagetoolkit.desenho.IDialog;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author 2091140052
 */
public class DialogBrilhoContraste extends javax.swing.JFrame {

    private IDialog dialog;

    /** Creates new form DialogBrilhoContraste */
    public DialogBrilhoContraste(final IDialog dialog) {
        initComponents();
        this.dialog = dialog;

        slBrilho.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                final int value = slBrilho.getValue();
                lblBrilho.setText(value + "");
                dialog.alterarBrilho(value);
            }
        });

        slContraste.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                final int value = slContraste.getValue();
                lblContraste.setText(value + "");
                dialog.alterarContraste(value);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        slBrilho = new javax.swing.JSlider();
        slContraste = new javax.swing.JSlider();
        lblBrilho = new javax.swing.JLabel();
        lblContraste = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Brilho:");

        jLabel2.setText("Contraste:");

        slBrilho.setValue(0);

        slContraste.setValue(0);

        lblBrilho.setText("0.0");

        lblContraste.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slContraste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(slBrilho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrilho, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContraste, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBrilho)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(slBrilho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraste)
                    .addComponent(slContraste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public JSlider getSlBrilho() {
        return slBrilho;
    }

    public JSlider getSlContraste() {
        return slContraste;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBrilho;
    private javax.swing.JLabel lblContraste;
    private javax.swing.JSlider slBrilho;
    private javax.swing.JSlider slContraste;
    // End of variables declaration//GEN-END:variables
}
