/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.tela;

import br.com.imagetoolkit.Binarizacao;
import br.com.imagetoolkit.ExibirImagem;
import br.com.imagetoolkit.ImageCanvas;
import br.com.imagetoolkit.JanelaAWT;
import br.com.imagetoolkit.Transformacao;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Jonas
 */
public class Main extends javax.swing.JFrame {
    
    private JanelaAWT janelaAWT;
    private BufferedImage bufferedImage;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCinza = new javax.swing.JButton();
        btnPretoBranco = new javax.swing.JButton();
        btnFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCinza.setText("Escala de cinza");
        btnCinza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCinzaActionPerformed(evt);
            }
        });

        btnPretoBranco.setText("Preto e branco");
        btnPretoBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretoBrancoActionPerformed(evt);
            }
        });

        btnFile.setText("Escolher arquivo");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnFile)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCinza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(btnPretoBranco)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCinza)
                    .addComponent(btnPretoBranco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFile)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
        File file = ExibirImagem.selectImage();
        try {
            loadImg(file);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFileActionPerformed

    private void btnCinzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCinzaActionPerformed
        BufferedImage cinza = Transformacao.transformeNivelCinza(bufferedImage, 0);
        ImageCanvas icCinza = new ImageCanvas(cinza);
        janelaAWT.setVisible(false);
        janelaAWT = new JanelaAWT(icCinza);
        janelaAWT.setVisible(true);
    }//GEN-LAST:event_btnCinzaActionPerformed

    private void btnPretoBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretoBrancoActionPerformed
         BufferedImage pretoBranco = Binarizacao.binarize(bufferedImage, 0, 100);
        ImageCanvas icPretoBranco = new ImageCanvas(pretoBranco);
        janelaAWT.setVisible(false);
        janelaAWT = new JanelaAWT(icPretoBranco);
        janelaAWT.setVisible(true);
    }//GEN-LAST:event_btnPretoBrancoActionPerformed

    private void loadImg(File file) throws IOException {
        bufferedImage = ImageIO.read(file);
        ImageCanvas imageCanvas = new ImageCanvas(bufferedImage);
        janelaAWT = new JanelaAWT(imageCanvas);
        janelaAWT.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCinza;
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnPretoBranco;
    // End of variables declaration//GEN-END:variables
}
